homework4 add LoanCalcController LoanCalcService LoanCalcRepository LoanCalcLogger
kbarysheva/qa-automation-java pull request #4
Opened 2021-08-15 21:57 UTC by kbarysheva

Создала каркас для приложения, которое будет рассматривать заявку на кредит.
Добавила файлы:
LoanCalcController - будет отвечать за валидацию значений и логирование
LoanCalcService - будет отвечает за вычисление бизнес логики
LoanCalcRepository - будет отвечать за хранение данных
LoanCalcLogger - будет отвечать за логирование
Имплементирован тест LoanCalcTest.
Проект успешно собирается.

2021-08-20 18:04 UTC, kbarysheva commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +        int localVar;
test comment

2021-08-20 18:05 UTC, niceta requested changes
123

2021-08-20 18:13 UTC, kbarysheva commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +        //log request
Удалила)

2021-08-20 18:14 UTC, kbarysheva commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcRepository.java
> +        int localVar = ++requestId;
Поправила

2021-08-20 18:15 UTC, kbarysheva commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +        int localVar;
Удалила

2021-08-20 18:15 UTC, kbarysheva commented on src/main/java/com/tinkoff/edu/app/LoanCalcService.java
> +        int localVar;
Удалила

2021-08-20 18:17 UTC, kbarysheva commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcService.java
> +     */
В дальнейшем здесь будет реализована логика логера (в следующих домашках)

2021-08-20 18:19 UTC, kbarysheva commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcRepository.java
> +     */
В дальнейшем здесь будет реализована логика хранения данных

2021-08-20 18:19 UTC, kbarysheva commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcLogger.java
> +     */
Здесь будет реализована логика валидации значений и логирования (в следующих домашках)

2021-08-24 07:19 UTC, niceta approved these changes

2021-08-24 07:19 UTC, merged